apiVersion: v2
name: sample-flask
type: application
version: "0.1.0"
appVersion: "latest"

dependencies:
  - name: postgresql
    version: 12.1.5        
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled  
    tags:
      - database