appName: sample-backend

# Application Environment
environment: development

deployment:
  replicas: 1

service:
  name: backend
  port: 5000

image:
  repository: sonld203/sample_flask_app
  tags: ""
  pullPolicy: Always

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1"
  
db_vol:
  claimName: database-pvc
  pv_size: 512Mi
  pvc_size: 400Mi

ingress:
  enabled: true
  name: backend
  hosts:
    - host: "myapp.local"
      paths:
        - path: "/"
          pathType: Prefix
          service:
            name: "backend"
            port: 5000

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: myapp
  primary:
    persistence:
      enabled: true
      storageClass: "standard"
      size: 2Gi
    extraConfiguration: |
      wal_level = logical
      max_wal_senders = 10
      max_replication_slots = 10
      max_connections = 200






