apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Values.appName | replace "_" "-" }}
  labels:
    {{ include "mychart.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
